Relax metric assert on runtime_control_metrics (#2476)
# Change Summary

This test has seen a few transient failures (commonly on Windows runs):
*
https://github.com/open-telemetry/otel-arrow/actions/runs/23760385085/job/69237797347?pr=2461
*
https://github.com/open-telemetry/otel-arrow/actions/runs/23809319658/job/69391753138?pr=2473

```
        FAIL [   0.033s] (1118/3015) otap-df-engine pipeline_ctrl::tests::test_runtime_control_metrics_track_due_work_dispatch
  stdout ───

    running 1 test
    test pipeline_ctrl::tests::test_runtime_control_metrics_track_due_work_dispatch ... FAILED

    failures:

    failures:
        pipeline_ctrl::tests::test_runtime_control_metrics_track_due_work_dispatch

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 191 filtered out; finished in 0.02s
    
  stderr ───

    thread 'pipeline_ctrl::tests::test_runtime_control_metrics_track_due_work_dispatch' (10136) panicked at crates\engine\src\pipeline_ctrl.rs:3209:36:
    assertion `left == right` failed: timer_tick.sent should count due timer dispatches
      left: 2
     right: 1
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The actual value is `2` instead of `1`.

From the context I can see, relaxing these assertions shouldn't
compromise the validity of the test.

## What issue does this PR close?

Attempts to resolve one of the flaky tests mentioned in #2464

## How are these changes tested?

Unit tests

## Are there any user-facing changes?

No