fix(tests): Switch from assert!(result.is_ok()) => result.unwrap() for CI diagnosability (#1937)
# Change Summary

Switch pattern from `assert!(result.is_ok())` to `result.unwrap()` in
exporter tests. This is to improve diagnostics for flakey tests in CI.
Currently, failures output the following which is not actionable:

```
    thread 'parquet_exporter::test::test_traces' (2500) panicked at crates\otap\src\parquet_exporter.rs:1299:21:
    assertion failed: exporter_result.is_ok()
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

With the change above, the error string from the result will be properly
logged.

## What issue does this PR close?

n/a

## How are these changes tested?

n/a

## Are there any user-facing changes?

No

---------

Co-authored-by: Joshua MacDonald <jmacd@users.noreply.github.com>