chore(ci): Skip j2 template configs in validate-configs check (#3244)
# Change Summary

As a byproduct of #3222, several config templates used in perf test
suites started failing the `validate-configs` CI check:
https://github.com/open-telemetry/otel-arrow/actions/runs/27148426271/job/80140238452?pr=3181

```log
  ❌ tools/pipeline_perf_test/test_suites/integration/templates/configs/engine/backpressure/otap-attr-otap.yaml
     
     ⚠️  WARNING: This binary was compiled in debug mode.
        Debug builds are NOT recommended for production, benchmarks, or performance testing.
        Use 'cargo build --release' for optimal performance.
     Error: Custom { kind: Other, error: "Invalid config for component `urn:otel:exporter:otap` in pipeline_group=default pipeline=main node=exporter: An invalid user configuration occurred: invalid grpc_endpoint \"http://{{backend_hostname}}:1235\": invalid uri character" }
Error: Process completed with exit code 1.
```

By updating those config filenames to `.yaml.j2`, they are skipped
during `validate-configs` execution. This pattern follows lots of other
configs in the repo, like those under `comparison_dashboard`.

## What issue does this PR close?

N/A

## How are these changes tested?

CI run

## Are there any user-facing changes?

No

### Changelog

<!--
User-facing changes need a .chloggen/*.yaml entry. Copy the
TEMPLATE.yaml
in go/.chloggen/ or rust/otap-dataflow/.chloggen/ and fill in the
fields.
If not required, include `chore` in the PR title.
-->

* [x] Added a `.chloggen/*.yaml` entry, OR this PR is a `chore`
(indicated in title).